package seeders

import (
	"fmt"
	"log"
	"time"

	"github.com/fadilmartias/dilz_code/apps/backend/app/models"

	"gorm.io/gorm"
)

func SeedPaymentMethod(db *gorm.DB, count int) {
	log.Printf("Seeding %d payment method...", count)
	var items []models.PaymentMethod
	bcaImg := "bca.png"
	mandiriImg := "mandiri.png"
	bniImg := "bni.png"
	briImg := "bri.png"
	permataImg := "permata.png"
	cimbImg := "cimb.png"
	gopayImg := "gopay.png"
	shopeepayImg := "shopeepay.png"
	alfamartImg := "alfamart.png"
	indomaretImg := "indomaret.png"
	qrisImg := "qris.png"
	danaImg := "dana.png"
	ccImg := "mastercard.png"

	ccDesc := "Credit / Debit Card Visa, Mastercard, JCB/AMEX"

	bcaDesc := "Virtual Account untuk BCA Bank"
	mandiriDesc := "Virtual Account untuk Mandiri Bank"
	bniDesc := "Virtual Account untuk BNI Bank"
	briDesc := "Virtual Account untuk BRI Bank"
	permataDesc := "Virtual Account untuk Permata Bank"
	cimbDesc := "Virtual Account untuk CIMB Bank"
	// Optional: predefined example
	sample := []models.PaymentMethod{
		{
			ID:                "PM1",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "bca",
			InvoiceCode:       "bca_va",
			Name:              "BCA",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         10000,
			MaxAmount:         999999999999,
			Img:               &bcaImg,
			Desc:              &bcaDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          false,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM2",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "mandiri",
			InvoiceCode:       "mandiri_bill",
			Name:              "Bank Mandiri",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         10000,
			MaxAmount:         999999999999,
			Img:               &mandiriImg,
			Desc:              &mandiriDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: true,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM3",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "bni",
			InvoiceCode:       "bni_va",
			Name:              "BNI",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         10000,
			MaxAmount:         999999999999,
			Img:               &bniImg,
			Desc:              &bniDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: true,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},

		{
			ID:                "PM4",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "bri",
			InvoiceCode:       "bri_va",
			Name:              "BRI",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         1,
			MaxAmount:         50000000000,
			Img:               &briImg,
			Desc:              &briDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: true,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM5",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "permata",
			InvoiceCode:       "permata_va",
			Name:              "Permata Bank",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         1,
			MaxAmount:         9999999999,
			Img:               &permataImg,
			Desc:              &permataDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: true,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM6",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DA",
			Order:             1,
			Type:              "bank_transfer",
			Code:              "cimb",
			InvoiceCode:       "cimb_va",
			Name:              "CIMB Niaga",
			FeeFixed:          4000,
			FeePercent:        0,
			PPN:               0.11,
			MinAmount:         1000,
			MaxAmount:         50000000,
			Img:               &cimbImg,
			Desc:              &cimbDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: true,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM7",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DE",
			Order:             1,
			Type:              "credit_card",
			Code:              "credit_card",
			InvoiceCode:       "credit_card",
			Name:              "VISA, Mastercard, JCB/AMEX",
			FeeFixed:          2000,
			PPN:               0.11,
			FeePercent:        0.029,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &ccImg,
			Desc:              &ccDesc,
			ExpirySeconds:     3 * 3600,
			IsActive:          false,
			IsReadyProduction: false,
			IsInternational:   true,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM8",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DB",
			Order:             1,
			Type:              "shopeepay",
			Code:              "shopeepay",
			InvoiceCode:       "shopeepay",
			Name:              "Shopeepay",
			FeeFixed:          0,
			PPN:               0.11,
			FeePercent:        0.02,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &shopeepayImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM9",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DB",
			Order:             1,
			Type:              "gopay",
			Code:              "gopay",
			InvoiceCode:       "gopay",
			Name:              "Gopay",
			FeeFixed:          0,
			PPN:               0.11,
			FeePercent:        0.02,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &gopayImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM10",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DB",
			Order:             1,
			Type:              "dana",
			Code:              "dana",
			InvoiceCode:       "dana",
			Name:              "Dana",
			FeeFixed:          0,
			PPN:               0.11,
			FeePercent:        0.015,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &danaImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM11",
			PaymentGatewayID:  "PG1",
			CategoryID:        "D10",
			Order:             1,
			Type:              "cstore",
			Code:              "alfamart",
			InvoiceCode:       "alfamart",
			Name:              "Alfamart",
			FeeFixed:          5000,
			PPN:               0.11,
			FeePercent:        0,
			MinAmount:         10000,
			MaxAmount:         5000000,
			Img:               &alfamartImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM12",
			PaymentGatewayID:  "PG1",
			CategoryID:        "D10",
			Order:             1,
			Type:              "cstore",
			Code:              "indomaret",
			InvoiceCode:       "indomaret",
			Name:              "Indomaret",
			FeeFixed:          5000,
			PPN:               0.11,
			FeePercent:        0,
			MinAmount:         10000,
			MaxAmount:         5000000,
			Img:               &indomaretImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM13",
			PaymentGatewayID:  "PG1",
			CategoryID:        "DD",
			Order:             1,
			Type:              "qris",
			Code:              "qris",
			InvoiceCode:       "other_qris",
			Name:              "QRIS",
			FeeFixed:          0,
			PPN:               0.11,
			FeePercent:        0.007,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &qrisImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
		{
			ID:                "PM14",
			PaymentGatewayID:  "PG2",
			CategoryID:        "DD",
			Order:             1,
			Type:              "qris",
			Code:              "qris",
			InvoiceCode:       "qris",
			Name:              "QRIS",
			FeeFixed:          0,
			PPN:               0.11,
			FeePercent:        0.007,
			MinAmount:         1,
			MaxAmount:         200000000,
			Img:               &qrisImg,
			Desc:              nil,
			ExpirySeconds:     3 * 3600,
			IsActive:          true,
			IsReadyProduction: false,
			IsInternational:   false,
			CreatedAt:         time.Now(),
			UpdatedAt:         time.Now(),
		},
	}
	items = append(items, sample...)

	// for i := 0; i < count; i++ {
	// 	item := factories.NewPaymentMethod()
	// 	// Optional: modify item before hashing/storing
	// 	items = append(items, item)
	// }

	result := db.CreateInBatches(&items, 100)
	if result.Error != nil {
		log.Printf("Could not seed payment method: %v", result.Error)
	} else {
		fmt.Printf("Seeded %d payment method successfully.\n", count)
	}
}
